# Advanced EV Health Monitoring Configuration

# Data paths
data:
  raw:
    maintenance: "archive/EV_Predictive_Maintenance_Dataset_15min.csv"
    patterns_dir: "archive (1)/"
    pattern_files:
      rare_user: "rare_user.csv"
      moderate_user: "moderate_user.csv"
      heavy_user: "heavy_user.csv"
      daily_user: "daily_user.csv"
  
  processed:
    dir: "data/processed/"
    maintenance_clean: "maintenance_cleaned.csv"
    patterns_combined: "patterns_combined.csv"
    
  merged:
    dir: "data/merged/"
    integrated_dataset: "ev_integrated_dataset.csv"
    
  features:
    dir: "data/features/"
    engineered_features: "engineered_features.csv"

# Model configuration
models:
  rul_prediction:
    algorithms: ["random_forest", "xgboost", "lstm"]
    target_column: "RUL"
    evaluation_metrics: ["mae", "rmse", "mape"]
    
  failure_prediction:
    algorithms: ["random_forest", "xgboost", "neural_network"]
    target_column: "Failure_Probability"
    evaluation_metrics: ["precision", "recall", "f1", "auc"]
    
  maintenance_scheduling:
    optimization_algorithm: "genetic_algorithm"
    cost_factors: ["labor", "parts", "downtime", "urgency"]

# Feature engineering
features:
  temporal:
    rolling_windows: [6, 12, 24, 48]  # hours
    lag_features: [1, 3, 6, 12]       # hours
    
  domain_specific:
    battery_degradation_rate: true
    driving_behavior_metrics: true
    component_stress_indicators: true
    seasonal_patterns: true

# User profiling
user_profiles:
  categories: ["rare_user", "moderate_user", "heavy_user", "daily_user"]
  clustering:
    algorithm: "kmeans"
    n_clusters: 4
    features: ["SOC", "SOH", "Motor_RPM", "Battery_Temp", "Charging_Cycles"]

# Maintenance recommendations
recommendations:
  prediction_horizon: 30  # days
  confidence_threshold: 0.8
  cost_optimization: true
  personalization: true

# Visualization
visualization:
  dashboard:
    refresh_rate: 60  # seconds
    components: ["health_overview", "predictions", "recommendations", "alerts"]
  
  plots:
    style: "seaborn-v0_8"
    color_palette: "husl"
    figure_size: [12, 8]

# Evaluation
evaluation:
  cross_validation:
    folds: 5
    strategy: "time_series_split"
  
  test_split:
    ratio: 0.2
    temporal_split: true
  
  metrics:
    business:
      cost_reduction_target: 0.15  # 15% reduction
      uptime_target: 0.95          # 95% uptime
      early_warning_days: 30

# Deployment
deployment:
  model_serving:
    framework: "mlflow"
    monitoring: true
    versioning: true
  
  real_time:
    batch_size: 100
    latency_target: 100  # milliseconds
